name: pa9es

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pa9es
    container_name: pa9es
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pa9es-data:/app/data
    networks:
      - tunnel-net

volumes:
  pa9es-data:

networks:
  tunnel-net:
    external: true
