// Usernames that can never be registered. Two categories: labels that would
// collide with real or future infrastructure hostnames, and brand names or
// lookalikes whose only use is phishing. Lowercase only — usernames are
// normalized before this check. Curated starting list; expand before launch.
// Unicode/Cyrillic homoglyphs need no entries here: the username charset is
// ASCII-only (see hostLabelSchema).
const RESERVED_USERNAMES = new Set<string>([
  // infrastructure & product
  "admin",
  "api",
  "app",
  "assets",
  "beta",
  "blog",
  "cdn",
  "dashboard",
  "demo",
  "dev",
  "docs",
  "download",
  "email",
  "files",
  "ftp",
  "help",
  "home",
  "imap",
  "images",
  "info",
  "legal",
  "mail",
  "mobile",
  "mx",
  "news",
  "ns1",
  "ns2",
  "official",
  "pa9es",
  "page",
  "pages",
  "pop",
  "portal",
  "press",
  "pricing",
  "privacy",
  "search",
  "settings",
  "site",
  "smtp",
  "staff",
  "staging",
  "static",
  "status",
  "store",
  "support",
  "system",
  "team",
  "terms",
  "test",
  "upload",
  "vpn",
  "web",
  "webmail",
  "webmaster",
  "www",
  // auth & money — phishing surface
  "account",
  "accounts",
  "auth",
  "billing",
  "checkout",
  "login",
  "logout",
  "noreply",
  "no-reply",
  "pay",
  "payment",
  "payments",
  "register",
  "root",
  "secure",
  "security",
  "signin",
  "signup",
  "ssl",
  "verify",
  "wallet",
  // standard mail-admin mailboxes
  "abuse",
  "hostmaster",
  "postmaster",
  // brands & known lookalikes (phishing bait)
  "amazon",
  "apple",
  "binance",
  "c0inbase",
  "coinbase",
  "facebook",
  "google",
  "instagram",
  "ledger",
  "meta",
  "metamask",
  "microsoft",
  "opensea",
  "paypa1",
  "paypal",
  "phantom",
  "rnetamask",
  "stripe",
  "trezor",
  "twitter",
  "uniswap",
]);

export { RESERVED_USERNAMES };
